### ISSUE TITLE
Fix occasional flashing

### ISSUE THREAD

**Issue by AAllport** [LocalBytes/localdeck-config#26]
It's a known issue that a different LED will occasionally flash green during a button press.
This is likely caused by electrical interference from the switches.

Testing suggests that limiting the drive current from the pin will suppress this behaviour to a point that I am struggling to replicate.

Eg
```diff
matrix_keypad:
  id: keypad
  keys: ABCDEFGHIJKLMNOPQRSTUVWX
  rows:
    - pin:
        number: GPIO21
       allow_other_uses: true
    - pin:
        number: GPIO20
       allow_other_uses: true
    - pin:
        number: GPIO3
       allow_other_uses: true
    - pin:
        number: GPIO7
       allow_other_uses: true
  columns:
-    - pin: GPIO0
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO0
-    - pin: GPIO1
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO1
-    - pin:  GPIO10
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO10
-    - pin: GPIO4
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO4
-    - pin: GPIO5
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO5
-    - pin: GPIO6
+    - pin: 
+        drive_strength: 5mA
+        number: GPIO6
```

**Comment by abstractvector** [comment]
I've manually applied the patch above to my config but it still seems to be happening. It's sporadic but easily reproducible - clicking around the buttons causes it pretty regularly.

**Comment by joshcliffejones** [comment]
This doesnt appear to have fixed the issue for me unfortunately.

**Comment by mcristina422** [comment]
Same with me. Even with the above patch, I can still easily reproduce the flashing. It's typically green, I think I've even seen white flashes as well

**Comment by markusressel** [comment]
I know this is closed, but I am struggling with severe flickering too.
Let me know if I should open a new issue about this.

Found this issue which is pretty recent, but it didn't fix the problem:
https://github.com/esphome/esphome/issues/10335

The issue doesn't show up if most of the LEDs are off, but the more LEDs are on, the more flickering happens across the whole board. The biggest problem is that the flickering doesn't only occur during color/brightness transitions, but the final color of the light is also wrong in many cases. So its not only flickering temporarily but showing the correct color in the end, its also showing the wrong color and never correcting itself.

I tried removing other components I don't really need like
improv, captive_portal, web_server, dashboard.

I also tried messing with the `drive_strength` property mentioned in this PR, but it didn't change anything.

I also tried to limit the brightness of all lights to 50% via the `color_correct` parameter, but it didn't change.

It is worth mentioning that I had similar problems on "regular" LED Strips when upgrading to the `esp32_rmt_led_strip` component as well, so I don't think this is necessarily a hardware problem, but its still a severe issue since it breaks functionality of the deck.

I also want to mention that I have two (very new, Jan 2026 order) units of the LocalDeck, and only one of them seems to be affected, at leas to the degree that it is genuinely "game breaking". I tried to switch USB cables, Power Plugs, and even used a PowerBank to see if anything changes, but it doesn't.

At this point I don't know what to try anymore :'(

**Comment by markusressel** [comment]
I just opened up the unit that's not working correctly, the board is labled as:

```
2025-05
0449
Local
Bytes
```

Is it possible this is an earlier revision that has an issue?
Or is the unit just defective?
The other unit I have doesn't seem to have any issues with flickering, I have tried many ways to introduce it (changing light colors very rapidly, using effects etc).

**EDIT: I found the issue!** Pressing on the contacts of "LED6" completely stops the flickering.
So it seems to me that this is a loose solder joint on the LED!
I will see if I can fix this by re-heating the LED legs briefly, to improve contact.

EDIT2: Resoldering the LED contacts fixed the issue! 🥳
